version: '3.6'
services:
  db:
    image: planqk/initialized-db:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - default
    secrets:
      - source: ssh_secret
        target: ssh_secret
networks:
  default:
    driver: bridge
secrets:
  ssh_secret:
    file: ./planqk-atlas-content-ssh_secret