version: '3.6'
services:
  db:
    image: planqk/initialized-db:latest
    environment:
      POSTGRES_USER: planqk
      POSTGRES_PASSWORD: planqk
      POSTGRES_DB: planqk
    ports:
      - "5432:5432"
    networks:
      - default
  qc-atlas:
    image: planqk/atlas:latest
    environment:
      POSTGRES_HOSTNAME: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: planqk
      POSTGRES_PASSWORD: planqk
      POSTGRES_DB: planqk
    ports:
      - "8080:8080"
    networks:
      - default
networks:
  default:
    driver: bridge
